# Generated by Django 3.2.9 on 2021-11-16 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('typescards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typecards',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='typescards.category'),
        ),
    ]
