# Generated by Django 3.2.9 on 2021-11-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typescards', '0002_alter_typecards_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typecards',
            name='year',
            field=models.TextField(),
        ),
    ]
